spring.application.name=ecom-application
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.type.descriptor.sql=TRACE
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
#http://localhost:8080/actuator/info
management.info.env.enabled=true
info.app.name=Ecommerce Application
info.app.description=App built by Us
info.app.version=1.0.0
management.endpoint.shutdown.enabled=true
server.port=${PORT:8080}
#spring.datasource.url=jdbc:h2:file:C:\Users\shbrk\Desktop\Data\Shabeer\Courses\SpringBoot\db\myDB


